### ISSUE TITLE
Remove .env from .gitignore?

### ISSUE THREAD

**Issue by jpollone** [unfolding-io/nebulix#10]
Not sure if this is standard practice that everyone knows about except me, but I had to remove `.env` from `.gitignore` in order to get Netlify and Vercel builds doing their build job.

My local .env is proper, but both Vercel and Netlify didn't know about it. (Aren't Vercel and Netlify just awesome?)

![screenshot 2023-10-11 0841@2x](https://github.com/unfolding-io/nebulix/assets/957276/1cb7cd0e-0026-4d8f-8ad1-63d5d4a85aa4)

**Comment by preetamslot** [comment]
It is best practice to keep your .env out of your git repo, most of the time you have some keys in there you don't want to make public, in my case my mailchimp api key.

If you use the "Vercel" or "Netlify" deploy button in the readme, the env will be generated. otherwise you have to do this manually.
